routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Customer Routes
Route::group(['middleware'=> ['auth']], function () {
    Route::get('/', [\App\Http\Controllers\CustomerController::class, 'home'])->name('home');
    Route::match(['GET', 'POST'], '/cart', [\App\Http\Controllers\CustomerController::class, 'cart'])->name('cart');
    Route::match(['GET', 'POST'], '/transactions', [\App\Http\Controllers\CustomerController::class, 'transactions'])->name('transactions');
    Route::get('/category/{category1?}/{category2?}/{category3?}/{category4?}/{category5?}', [\App\Http\Controllers\CustomerController::class, 'category'])->name('category');
    Route::get('/brand/{brand}', [\App\Http\Controllers\CustomerController::class, 'brand'])->name('brand');
});


// Admin & Staff Routes
Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {

    Route::get('/', [\App\Http\Controllers\AdminController::class, 'dashboard'])->name('dashboard');

    Route::resource('/transactions', \App\Http\Controllers\TransactionController::class);
    Route::get('/report', [\App\Http\Controllers\TransactionController::class, 'report'])->name('report');

    Route::resource('/products', \App\Http\Controllers\ProductController::class);
    Route::resource('/customers', \App\Http\Controllers\CustomerController::class);
    Route::resource('/categories', \App\Http\Controllers\CategoryController::class);
    Route::resource('/brands', \App\Http\Controllers\BrandController::class);
    Route::resource('/users', \App\Http\Controllers\UserController::class);
});

Auth::routes();

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function getImageAttribute($image)
    {
        return asset('storage' . $image);
    }

    public function brand()
    {
        return $this->belongsTo(ProductBrand::class, 'brand_id');
    }

    public function category()
    {
        return $this->belongsTo(ProductCategory::class, 'category_id');
    }

    public function getPriceAttribute()
    {
        return $this->formatCurrency($this->sell_price);
    }

    public function getFromPriceAttribute()
    {
        return $this->formatCurrency($this->sell_price + ($this->sell_price * 0.40));
    }

    public function formatCurrency($number) {
        return 'IDR ' . number_format($number, 0, ',', '.');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::orderBy('category_id', 'asc')->orderBy('brand_id', 'asc')->get();
        return view('product.index', compact('products'));
    }

    public function create()
    {
        $product = null;
        return view('product.form', compact('product'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required'],
            'description' => ['required'],
            'image' => ['required', 'file', 'mimes:png,jpg,jpeg'],
            'category_id' => ['required', 'exists:product_categories,id'],
            'brand_id' => ['required', 'exists:product_brands,id'],
            'stock' => ['required', 'numeric'],
            'buy_price' => ['required', 'numeric'],
            'sell_price' => ['required', 'numeric'],
        ]);

        $image = $request->file('image');
        $filename = '/products/' . uniqid() . '.' . $image->getClientOriginalExtension();
        $image->storeAs('public', $filename);

        Product::create([
            'name' => $request->name,
            'description' => $request->description,
            'category_id' => $request->category_id,
            'brand_id' => $request->brand_id,
            'stock' => $request->stock,
            'buy_price' => $request->buy_price,
            'sell_price' => $request->sell_price,
            'image' => $filename,
        ]);

        return redirect()->back()->with('msg', 'Product created successfully');
    }

    public function edit(Product $product)
    {
        return view('product.form', compact('product'));
    }

    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name' => ['required'],
            'description' => ['required'],
            'image' => ['file', 'mimes:png,jpg,jpeg'],
            'category_id' => ['required', 'exists:product_categories,id'],
            'brand_id' => ['required', 'exists:product_brands,id'],
            'stock' => ['required', 'numeric'],
            'buy_price' => ['required', 'numeric'],
            'sell_price' => ['required', 'numeric'],
        ]);

        if ($request->image) {
            $image = $request->file('image');
            $filename = '/products/' . uniqid() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('public', $filename);

            $product->update([
                'image' => $filename,
            ]);
        }

        $product->update([
            'name' => $request->name,
            'description' => $request->description,
            'category_id' => $request->category_id,
            'brand_id' => $request->brand_id,
            'stock' => $request->stock,
            'buy_price' => $request->buy_price,
            'sell_price' => $request->sell_price,
        ]);

        return redirect()->back()->with('msg', 'Product updated successfully');
    }
}

resources/views/product/form.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">{{ isset($product) ? 'Edit' : 'Add' }} Product</h4>
        <div class="row">
            <div class="col-md-4">
                @include('layouts.alert')
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0">
                            Form {{ isset($product) ? 'Edit' : 'Add' }} Product
                        </h5>
                    </div>
                    <div class="card-body p-4 border-top">
                        <form action="{{isset($product) ? route('admin.products.update', $product) : route('admin.products.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @if(isset($product))
                                @method('PUT')
                            @endif
                            <div class="form-group mb-2">
                                <label for="name">Name</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{$product->name ?? (old('name') ?? '')}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="description">Description</label>
                                <textarea name="description" id="description" class="form-control" cols="30" rows="5">{{$product->description ?? (old('description') ?? '')}}</textarea>
                            </div>
                            <div class="form-group mb-2">
                                <label for="category_id">Category</label>
                                <select name="category_id" id="category_id" class="form-control">
                                    @foreach(\App\Models\ProductCategory::all() as $category)
                                    <option value="{{$category->id}}" {{$product->category_id ?? (old('category_id') ?? '') == $category->id ? 'selected' : ''}}>
                                        {{$category->name}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group mb-2">
                                <label for="brand_id">Brand</label>
                                <select name="brand_id" id="brand_id" class="form-control">
                                    @foreach(\App\Models\ProductBrand::all() as $brand)
                                        <option value="{{$brand->id}}" {{$product->brand_id ?? (old('brand_id') ?? '') == $brand->id ? 'selected' : ''}}>
                                            {{$brand->name}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group mb-4">
                                @if(isset($product))
                                    <div class="mb-2 mt-3">
                                        <img src="{{$product->image}}" style="width: 100px;" alt="image">
                                    </div>
                                @endif
                                <label for="image">Image</label>
                                <input type="file" id="image" name="image" class="form-control">
                            </div>
                            <div class="form-group mb-2">
                                <label for="stock">Stock</label>
                                <input type="number" min="0" name="stock" id="stock" class="form-control" value="{{$product->stock ?? (old('stock') ?? '')}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="buy_price">Buy Price</label>
                                <input type="number" min="0" name="buy_price" id="buy_price" class="form-control" value="{{$product->buy_price ?? (old('buy_price') ?? '')}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="sell_price">Sell Price</label>
                                <input type="number" min="0" name="sell_price" id="sell_price" class="form-control" value="{{$product->sell_price ?? (old('sell_price') ?? '')}}">
                            </div>
                            <div class="mt-4 d-flex align-items-center justify-content-between">
                                <a href="{{route('admin.products.index')}}" class="btn btn-outline-primary">Cancel</a>

                                <button type="submit" class="btn btn-primary">
                                    {{isset($product) ? 'Update' : 'Save'}}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">Products</h4>
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">
                    List Products
                </h5>
                <a href="{{route('admin.products.create')}}" class="d-flex align-items-center">Add New Product</a>
            </div>
            <div class="card-body p-4 border-top">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Image</td>
                        <td>Category</td>
                        <td>Brand</td>
                        <td class="text-center">Stock</td>
                        <td class="text-end">Sell Price</td>
                        <td>Created Date</td>
                        <td class="text-center">Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $i => $product)
                        <tr>
                            <td>{{$i+1}}</td>
                            <td>{{$product->name}}</td>
                            <td>{{$product->name}}</td>
                            <td>{{$product->category->name}}</td>
                            <td>{{$product->brand->name}}</td>
                            <td class="text-center">{{$product->stock}}</td>
                            <td class="text-end">{{$product->price}}</td>
                            <td>{{$product->created_at->format('F j, Y H:i')}}</td>
                            <td class="text-center">
                                <a href="{{route('admin.products.edit', $product)}}" data-bs-toggle="tooltip" data-bs-title="Edit">
                                    <i class="ti ti-edit"></i>
                                </a>
                                <a href="{{route('admin.products.destroy', $product)}}" data-bs-toggle="tooltip" data-bs-title="Delete" class="ms-2">
                                    <i class="ti ti-trash"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection