routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Customer Routes
Route::group(['middleware'=> ['auth']], function () {
    Route::get('/', [\App\Http\Controllers\CustomerController::class, 'home'])->name('home');
    Route::match(['GET', 'POST'], '/cart', [\App\Http\Controllers\CustomerController::class, 'cart'])->name('cart');
    Route::match(['GET', 'POST'], '/transactions', [\App\Http\Controllers\CustomerController::class, 'transactions'])->name('transactions');
    Route::get('/category/{category1?}/{category2?}/{category3?}/{category4?}/{category5?}', [\App\Http\Controllers\CustomerController::class, 'category'])->name('category');
    Route::get('/brand/{brand}', [\App\Http\Controllers\CustomerController::class, 'brand'])->name('brand');
});


// Admin & Staff Routes
Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {

    Route::get('/', [\App\Http\Controllers\AdminController::class, 'dashboard'])->name('dashboard');

    Route::resource('/transactions', \App\Http\Controllers\TransactionController::class);
    Route::get('/report', [\App\Http\Controllers\TransactionController::class, 'report'])->name('report');

    Route::resource('/products', \App\Http\Controllers\ProductController::class);
    Route::resource('/customers', \App\Http\Controllers\CustomerController::class);
    Route::resource('/categories', \App\Http\Controllers\CategoryController::class);
    Route::resource('/brands', \App\Http\Controllers\BrandController::class);
    Route::resource('/users', \App\Http\Controllers\UserController::class);
});

Auth::routes();

app/Models/ProductBrand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductBrand extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function getLogoAttribute($image)
    {
        return asset('storage' . $image);
    }
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductBrand;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class BrandController extends Controller
{
    public function index()
    {
        $brands = ProductBrand::orderBy('name', 'asc')->get();
        return view('brand.index', compact('brands'));
    }

    public function create()
    {
        $brand = null;
        return view('brand.form', compact('brand'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required'],
            'logo' => ['required', 'file', 'mimes:png,jpg,jpeg'],
        ]);

        $image = $request->file('logo');
        $filename = '/brands/' . uniqid() . '.' . $image->getClientOriginalExtension();
        $image->storeAs('public', $filename);

        ProductBrand::create([
            'name' => $request->name,
            'slug' => Str::slug($request->name),
            'logo' => $filename,
        ]);

        return redirect()->back()->with('msg', 'Brand created successfully');
    }

    public function edit(ProductBrand $brand)
    {
        return view('brand.form', compact('brand'));
    }

    public function update(Request $request, ProductBrand $brand)
    {
        $request->validate([
            'name' => ['required'],
            'logo' => [ 'file', 'mimes:png,jpg,jpeg'],
        ]);

        $image = $request->file('logo');
        if ($image) {
            $filename = '/brands/' . uniqid() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('public', $filename);
            $brand->update([
                'logo' => $filename,
            ]);
        }

        $brand->update([
            'name' => $request->name,
            'slug' => Str::slug($request->name),
        ]);

        return redirect()->back()->with('msg', 'Brand updated successfully');
    }
}

resources/views/brand/form.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">{{ isset($brand) ? 'Edit' : 'Add' }} Brand</h4>
        <div class="row">
            <div class="col-md-4">
                @include('layouts.alert')
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0">
                            Form {{ isset($brand) ? 'Edit' : 'Add' }} Brand
                        </h5>
                    </div>
                    <div class="card-body p-4 border-top">
                        <form action="{{isset($brand) ? route('admin.brands.update', $brand) : route('admin.brands.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @if(isset($brand))
                                @method('PUT')
                            @endif
                            <div class="form-group mb-2">
                                <label for="name">Name</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{$brand->name ?? (old('name') ?? '')}}">
                            </div>
                            <div class="form-group mb-4">
                                @if(isset($brand))
                                    <div class="mb-2 mt-3">
                                        <img src="{{$brand->logo}}" style="width: 100px;" alt="image">
                                    </div>
                                @endif
                                <label for="logo">Logo</label>
                                <input type="file" id="logo" name="logo" class="form-control">
                            </div>
                            <div class="mt-4 d-flex align-items-center justify-content-between">
                                <a href="{{route('admin.brands.index')}}" class="btn btn-outline-primary">Cancel</a>

                                <button type="submit" class="btn btn-primary">
                                    {{isset($brand) ? 'Update' : 'Save'}}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/brand/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">Brands</h4>
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">
                    List Brands
                </h5>
                <a href="{{route('admin.brands.create')}}" class="d-flex align-items-center">Add New Brand</a>
            </div>
            <div class="card-body p-4 border-top">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Created Date</td>
                        <td class="text-center">Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($brands as $i => $brand)
                        <tr>
                            <td>{{$i+1}}</td>
                            <td>{{$brand->name}}</td>
                            <td>{{$brand->created_at->format('F j, Y H:i')}}</td>
                            <td class="text-center">
                                <a href="{{route('admin.brands.edit', $brand)}}" data-bs-toggle="tooltip" data-bs-title="Edit">
                                    <i class="ti ti-edit"></i>
                                </a>
                                <a href="{{route('admin.brands.destroy', $brand)}}" data-bs-toggle="tooltip" data-bs-title="Delete" class="ms-2">
                                    <i class="ti ti-trash"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection