routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Customer Routes
Route::group(['middleware'=> ['auth']], function () {
    Route::get('/', [\App\Http\Controllers\CustomerController::class, 'home'])->name('home');
    Route::match(['GET', 'POST'], '/cart', [\App\Http\Controllers\CustomerController::class, 'cart'])->name('cart');
    Route::match(['GET', 'POST'], '/transactions', [\App\Http\Controllers\CustomerController::class, 'transactions'])->name('transactions');
    Route::get('/category/{category1?}/{category2?}/{category3?}/{category4?}/{category5?}', [\App\Http\Controllers\CustomerController::class, 'category'])->name('category');
    Route::get('/brand/{brand}', [\App\Http\Controllers\CustomerController::class, 'brand'])->name('brand');
});


// Admin & Staff Routes
Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {

    Route::get('/', [\App\Http\Controllers\AdminController::class, 'dashboard'])->name('dashboard');

    Route::resource('/transactions', \App\Http\Controllers\TransactionController::class);
    Route::get('/report', [\App\Http\Controllers\TransactionController::class, 'report'])->name('report');

    Route::resource('/products', \App\Http\Controllers\ProductController::class);
    Route::resource('/customers', \App\Http\Controllers\CustomerController::class);
    Route::resource('/categories', \App\Http\Controllers\CategoryController::class);
    Route::resource('/brands', \App\Http\Controllers\BrandController::class);
    Route::resource('/users', \App\Http\Controllers\UserController::class);
});

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = [];

    public function customer()
    {
        return $this->hasOne(Customer::class);
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $users = User::orderBy('role_id', 'asc')->orderBy('created_at', 'desc')->get();
        return view('user.index', compact('users'));
    }

    public function create()
    {
        $user = null;
        return view('user.form', compact('user'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required'],
            'sex' => ['required', 'in:Male,Female'],
            'username' => ['required', 'unique:users,username'],
            'password' => ['required', 'confirmed', 'min:6'],
            'role_id' => ['required', 'in:1,2']
        ]);

        User::create([
            'name' => $request->name,
            'sex' => $request->sex,
            'username' => $request->username,
            'password' => bcrypt($request->password),
            'role_id' => $request->role_id
        ]);

        return redirect()->back()->with('msg', 'User created successfully');
    }

    public function edit(User $user)
    {
        return view('user.form', compact('user'));
    }

    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => ['required'],
            'sex' => ['required', 'in:Male,Female'],
            'username' => ['required', 'unique:users,username'],
            'role_id' => ['required', 'in:1,2']
        ]);

        $user->update([
            'name' => $request->name,
            'sex' => $request->sex,
            'username' => $request->username,
        ]);

        return redirect()->back()->with('msg', 'User updated successfully');
    }
}

resources/views/user/form.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">{{ isset($user) ? 'Edit' : 'Add' }} User</h4>
        <div class="row">
            <div class="col-md-4">
                @include('layouts.alert')
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0">
                            Form {{ isset($user) ? 'Edit' : 'Add' }} User
                        </h5>
                    </div>
                    <div class="card-body p-4 border-top">
                        <form action="{{isset($user) ? route('admin.users.update', $user) : route('admin.users.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @if(isset($user))
                                @method('PUT')
                            @endif
                            <div class="form-group mb-2">
                                <label for="role_id">Role</label>
                                <select name="role_id" id="role_id" class="form-control">
                                    <option value="1" {{$user->role_id ?? (old('role_id') ?? '') == '1' ? 'selected' : ''}}>Administrator</option>
                                    <option value="2" {{$user->role_id ?? (old('role_id') ?? '') == '2' ? 'selected' : ''}}>Staff</option>
                                </select>
                            </div>
                            <div class="form-group mb-2">
                                <label for="name">Name</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{$user->name ?? (old('name') ?? '')}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="sex">Gender</label>
                                <select name="sex" id="sex" class="form-control">
                                    <option value="Male" {{$user->sex ?? (old('sex') ?? '') == 'Male' ? 'selected' : ''}}>Male</option>
                                    <option value="Female" {{$user->sex ?? (old('sex') ?? '') == 'Female' ? 'selected' : ''}}>Female</option>
                                </select>
                            </div>
                            <hr class="mb-4">
                            <div class="form-group mb-2">
                                <label for="username">Username</label>
                                <input type="text" name="username" id="username" class="form-control" value="{{$user->user->username ?? (old('username') ?? '')}}">
                            </div>
                            @if(!isset($user))
                            <div class="form-group mb-2">
                                <label for="password">Password</label>
                                <input type="password" name="password" id="password" class="form-control" value="">
                            </div>
                            <div class="form-group mb-2">
                                <label for="password_confirmation">Confirm Password</label>
                                <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" value="">
                            </div>
                            @endif
                            <div class="mt-4 d-flex align-items-center justify-content-between">
                                <a href="{{route('admin.users.index')}}" class="btn btn-outline-primary">Cancel</a>

                                <button type="submit" class="btn btn-primary">
                                    {{isset($user) ? 'Update' : 'Save'}}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">Users</h4>
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">
                    List Users
                </h5>
                <a href="{{route('admin.users.create')}}" class="d-flex align-items-center">Add New User</a>
            </div>
            <div class="card-body p-4 border-top">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Gender</td>
                        <td>Username</td>
                        <td>Role</td>
                        <td>Created Date</td>
                        <td class="text-center">Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $i => $user)
                        <tr>
                            <td>{{$i+1}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->sex}}</td>
                            <td>{{$user->username}}</td>
                            <td>{{$user->role->name}}</td>
                            <td>{{$user->created_at->format('F j, Y H:i')}}</td>
                            <td class="text-center">
                                <a href="{{route('admin.users.edit', $user)}}" data-bs-toggle="tooltip" data-bs-title="Edit">
                                    <i class="ti ti-edit"></i>
                                </a>
                                <a href="{{route('admin.users.destroy', $user)}}" data-bs-toggle="tooltip" data-bs-title="Delete" class="ms-2">
                                    <i class="ti ti-trash"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection