routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Customer Routes
Route::group(['middleware'=> ['auth']], function () {
    Route::get('/', [\App\Http\Controllers\CustomerController::class, 'home'])->name('home');
    Route::match(['GET', 'POST'], '/cart', [\App\Http\Controllers\CustomerController::class, 'cart'])->name('cart');
    Route::match(['GET', 'POST'], '/transactions', [\App\Http\Controllers\CustomerController::class, 'transactions'])->name('transactions');
    Route::get('/category/{category1?}/{category2?}/{category3?}/{category4?}/{category5?}', [\App\Http\Controllers\CustomerController::class, 'category'])->name('category');
    Route::get('/brand/{brand}', [\App\Http\Controllers\CustomerController::class, 'brand'])->name('brand');
});


// Admin & Staff Routes
Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {

    Route::get('/', [\App\Http\Controllers\AdminController::class, 'dashboard'])->name('dashboard');

    Route::resource('/transactions', \App\Http\Controllers\TransactionController::class);
    Route::get('/report', [\App\Http\Controllers\TransactionController::class, 'report'])->name('report');

    Route::resource('/products', \App\Http\Controllers\ProductController::class);
    Route::resource('/customers', \App\Http\Controllers\CustomerController::class);
    Route::resource('/categories', \App\Http\Controllers\CategoryController::class);
    Route::resource('/brands', \App\Http\Controllers\BrandController::class);
    Route::resource('/users', \App\Http\Controllers\UserController::class);
});

Auth::routes();

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getNameAttribute()
    {
        return $this->user->name;
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function getImageAttribute($image)
    {
        return asset('storage' . $image);
    }

    public function brand()
    {
        return $this->belongsTo(ProductBrand::class, 'brand_id');
    }

    public function category()
    {
        return $this->belongsTo(ProductCategory::class, 'category_id');
    }

    public function getPriceAttribute()
    {
        return $this->formatCurrency($this->sell_price);
    }

    public function getFromPriceAttribute()
    {
        return $this->formatCurrency($this->sell_price + ($this->sell_price * 0.40));
    }

    public function formatCurrency($number) {
        return 'IDR ' . number_format($number, 0, ',', '.');
    }
}

app/Models/ProductBrand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductBrand extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function getLogoAttribute($image)
    {
        return asset('storage' . $image);
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Transaction;
use App\Models\User;
use Cassandra\Custom;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Route;

class CustomerController extends Controller
{

    public function home()
    {
        if (auth()->user() && auth()->user()->role_id != 3) {
            return redirect()->route('admin.dashboard');
        }

        $start = date('Y-m-d', strtotime('-14 days', strtotime(date('Y-m-d'))));
        $end = date('Y-m-d');

        $transactions = Transaction::whereBetween('created_at', [$start, $end])->orderBy('created_at', 'asc')->get();

        $products_counted = Product::all()->map(function($product) use ($transactions) {
            $product->sold = $transactions->flatMap(fn($transaction) => $transaction->products)->filter(fn($product2) => $product->id == $product2->id)->count();
            return $product;
        });

        $popular_products = $products_counted->sortByDesc('sold')->values()->slice(0, 4);

        $new_products = Product::orderBy('created_at', 'desc')->take(8)->get();

        return view('customer.home', compact('popular_products', 'new_products'));
    }

    public function category()
    {
        $args = func_get_args();

        $category = ProductCategory::whereSlug($args[count($args)-1])->first();

        if (request()->path() !== 'category/' . $category->full_slug) {
            return abort(404);
        }

        return view('customer.category', compact('category'));
    }

    public function cart(Request $request)
    {
        if ($request->isMethod('POST')) {
            $cart = (array) (request()->hasCookie('cart') ? json_decode(request()->cookie('cart')) : []);

            if (isset($cart[$request->product_id])) {
                $cart[$request->product_id] += 1;
            } else {
                $cart[$request->product_id] = 1;
            }

            Cookie::queue(Cookie::make('cart', json_encode($cart), 60));

            return response()->json(['message' => 'Product added to cart', 'total_cart' => collect($cart)->reduce(fn($carry, $item) => $carry+=$item, 0)]);
        }
        return view('customer.cart');
    }

    public function transactions(Request $request)
    {
        if ($request->isMethod('POST')) {
            if (auth()->guest()) {
                return redirect()->route('login');
            }

            $cart = collect((array) (request()->hasCookie('cart') ? json_decode(request()->cookie('cart')) : []))->map(function($quantity, $product_id) {
                $product = Product::find($product_id);
                return [
                    'quantity' => $quantity,
                    'total' => $product->sell_price * $quantity
                ];
            });

            $transaction = auth()->user()->customer->transactions()->create([
                'code' => strtoupper(uniqid()),
                'total' => $cart->reduce(fn($total, $product) => $total+=$product['total'], 0),
                'status' => 'pending',
            ]);
            $transaction->products()->sync( $cart );

            Cookie::queue(Cookie::make('cart', null, 0));

            return redirect()->route('transactions');
        }
        return view('customer.transactions');
    }

    public function index()
    {
        $customers = User::where('role_id', 3)->orderBy('created_at', 'desc')->get();
        return view('customer.index', compact('customers'));
    }

    public function create()
    {
        $customer = null;
        return view('customer.form', compact('customer'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required'],
            'sex' => ['required', 'in:Male,Female'],
            'username' => ['required', 'unique:users,username'],
            'password' => ['required', 'confirmed', 'min:6'],
            'born_place' => ['required'],
            'born_date' => ['required', 'date_format:Y-m-d'],
            'id_card_photo' => ['required', 'file', 'mimes:png,jpg,jpeg'],
            'address' => ['required'],
        ]);

        $id_card = $request->file('id_card_photo');
        $filename = '/id_cards/' . uniqid() . '.' . $id_card->getClientOriginalExtension();
        $id_card->storeAs('public', $filename);

        $user = User::create([
            'name' => $request->name,
            'sex' => $request->sex,
            'username' => $request->username,
            'password' => bcrypt($request->password),
            'role_id' => 3
        ]);

        $user->customer()->create([
            'id_card_photo' => $filename,
            'born_place' => $request->born_place,
            'born_date' => $request->born_date,
            'address' => $request->address,
        ]);

        return redirect()->back()->with('msg', 'Customer created successfully');
    }

    public function edit(Customer $customer)
    {
        return view('customer.form', compact('customer'));
    }

    public function update(Request $request, Customer $customer)
    {
        $request->validate([
            'name' => ['required'],
            'sex' => ['required', 'in:Male,Female'],
            'username' => ['required', 'unique:users,username,' . $customer->user->id],
            'born_place' => ['required'],
            'born_date' => ['required', 'date_format:Y-m-d'],
            'id_card_photo' => ['file', 'mimes:png,jpg,jpeg'],
            'address' => ['required'],
        ]);

        $id_card = $request->file('id_card_photo');
        if ($id_card) {
            $filename = '/id_cards/' . uniqid() . '.' . $id_card->getClientOriginalExtension();
            $id_card->storeAs('public', $filename);
        } else {
            $filename = $customer->id_card_photo;
        }

        $customer->update([
            'id_card_photo' => $filename,
            'born_place' => $request->born_place,
            'born_date' => $request->born_date,
            'address' => $request->address,
        ]);

        $customer->user->update([
            'name' => $request->name,
            'sex' => $request->sex,
            'username' => $request->username,
        ]);

        return redirect()->back()->with('msg', 'Customer updated successfully');
    }
}

resources/views/customer/cart.blade.php
@extends('layouts.customer')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3">My Shopping Bag ({{$cart->reduce(fn($carry, $item) => $carry+=$item, 0)}} Items)</h4>

        <div class="card">
            <div class="card-body">
                    <!-- Cart -->
                    <div id="checkout-cart" class="content active dstepper-block fv-plugins-bootstrap5 fv-plugins-framework">
                        <div class="row">
                            <!-- Cart left -->
                            <div class="col-xl-8 mb-3 mb-xl-0">

                                <ul class="list-group mb-3">
                                    @foreach($cart as $product_id => $quantity)
                                    @php
                                    $product = \App\Models\Product::find($product_id);
                                    @endphp
                                    <li class="list-group-item p-4">
                                        <div class="d-flex gap-3">
                                            <div class="flex-shrink-0 d-flex align-items-center">
                                                <img src="{{$product->image}}" alt="google home" class="w-px-100">
                                            </div>
                                            <div class="flex-grow-1">
                                                <div class="row align-items-center">
                                                    <div class="col-md-8">
                                                        <p class="me-3 mb-1">
                                                            <a href="javascript:void(0)" class="text-body">{{$product->name}}</a>
                                                        </p>
                                                        <div class="text-muted mb-3 d-flex flex-wrap">
                                                            <span class="me-1">Brand:</span>
                                                            <a href="javascript:void(0)" class="me-3">
                                                                {{$product->brand->name}}
                                                            </a>
                                                        </div>
                                                        <div class="d-flex align-items-center">
                                                            Qty:
                                                            <span class="mx-3">
                                                                {{$quantity}}
                                                            </span>
                                                        </div>
{{--                                                        <input type="number" class="form-control form-control-sm w-px-75" value="{{$quantity}}" min="1" max="{{$product->stock}}">--}}
                                                    </div>
                                                    <div class="col-md-4">
                                                        <div class="text-md-end">
                                                            <button type="button" class="btn-close btn-pinned" aria-label="Close"></button>
                                                            <div class="my-2 my-md-4 mb-md-5">
{{--                                                                <s class="text-muted me-2">{{$product->from_price}}</s>--}}
                                                                <span class="text-primary">{{$product->formatCurrency($product->sell_price * $quantity)}}</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    @endforeach
                                </ul>

                            </div>

                            <!-- Cart right -->
                            <div class="col-xl-4">
                                <div class="border rounded p-4 mb-3 pb-3">

                                    <!-- Price Details -->
                                    <h6>Price Details</h6>
                                    <dl class="row mb-0">

                                        <dt class="col-6 fw-normal">Order Total</dt>
                                        <dd class="col-6 text-end">
                                            {{\App\Models\Product::first()->formatCurrency($cart->reduce(fn($total, $quantity, $id) => $total += \App\Models\Product::find($id)->sell_price * $quantity, 0))}}
                                        </dd>

                                    </dl>

                                    <hr class="mx-n4">
                                    <dl class="row mb-0">
                                        <dt class="col-6">Total</dt>
                                        <dd class="col-6 fw-semibold text-end mb-0">{{\App\Models\Product::first()->formatCurrency($cart->reduce(fn($total, $quantity, $id) => $total += \App\Models\Product::find($id)->sell_price * $quantity, 0))}}</dd>
                                    </dl>
                                </div>
                                <div class="d-grid">
                                    <form action="{{route('transactions')}}" method="POST">
                                        @csrf
                                        <button type="submit" class="btn btn-primary">Checkout</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>
@endsection

resources/views/customer/category.blade.php
@extends('layouts.customer')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3">{{$category->name}}</h4>

        <div class="row">
            @foreach($category->products as $product)
            <div class="col-md-3">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="d-flex align-items-center mb-3">
                            <img src="{{$product->brand->logo}}" alt="{{$product->brand->name}}" style="height: 32px;" class="me-2">
                            {{--                            <h6 class="card-subtitle text-muted m-0">--}}
                            {{--                                {{$product->brand->name}}--}}
                            {{--                            </h6>--}}
                        </div>
                        <h5 class="card-title">{{$product->name}}</h5>
                        <img class="img-fluid d-flex mx-auto my-3 rounded" src="{{ $product->image }}" alt="{{ $product->name }}">
                        <div class="mb-3">
                            <h4 class="card-text mb-0">
                                {{$product->price}}
                            </h4>
                            <h6 class="text-warning fw-normal">
                                <del>{{$product->from_price}}</del>
                            </h6>
                        </div>
                        <div class="row align-items-center d-flex">
                            <div class="col-7">
                                <a href="javascript:void(0);" class="btn btn-outline-primary w-100 add-to-cart" data-id="{{$product->id}}">Add to Cart</a>
                            </div>
                            <div class="col-5">
                                <a href="javascript:void(0);" class="card-link w-100 text-center">View Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/customer/form.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">{{ isset($customer) ? 'Edit' : 'Add' }} Customer</h4>
        <div class="row">
            <div class="col-md-4">
                @include('layouts.alert')
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0">
                            Form {{ isset($customer) ? 'Edit' : 'Add' }} Customer
                        </h5>
                    </div>
                    <div class="card-body p-4 border-top">
                        <form action="{{isset($customer) ? route('admin.customers.update', $customer) : route('admin.customers.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @if(isset($customer))
                                @method('PUT')
                            @endif
                            <div class="form-group mb-2">
                                <label for="name">Name</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{$customer->name ?? (old('name') ?? '')}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="sex">Gender</label>
                                <select name="sex" id="sex" class="form-control">
                                    <option value="Male" {{$customer->sex ?? (old('sex') ?? '') == 'Male' ? 'selected' : ''}}>Male</option>
                                    <option value="Female" {{$customer->sex ?? (old('sex') ?? '') == 'Female' ? 'selected' : ''}}>Female</option>
                                </select>
                            </div>
                            <div class="form-group mb-2">
                                <label for="born_place">Born Place</label>
                                <input type="text" name="born_place" id="born_place" class="form-control" value="{{$customer->born_place ?? (old('born_place') ?? '')}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="born_date">Born Date</label>
                                <input type="date" name="born_date" id="born_date" class="form-control" value="{{$customer->born_date ?? (old('born_date') ?? '')}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="address">Address</label>
                                <textarea name="address" id="address" class="form-control" cols="30" rows="5">{{$customer->address ?? (old('address') ?? '')}}</textarea>
                            </div>
                            <div class="form-group mb-4">
                                @if(isset($customer))
                                    <div class="mb-2 mt-3">
                                        <img src="{{asset('storage' . $customer->id_card_photo)}}" style="width: 100px;" alt="image">
                                    </div>
                                @endif
                                <label for="id_card_photo">Change ID Card Photo</label>
                                <input type="file" id="id_card_photo" name="id_card_photo" class="form-control">
                            </div>
                            <hr class="mb-4">
                            <div class="form-group mb-2">
                                <label for="username">Username</label>
                                <input type="text" name="username" id="username" class="form-control" value="{{$customer->user->username ?? (old('username') ?? '')}}">
                            </div>
                            @if(!isset($customer))
                            <div class="form-group mb-2">
                                <label for="password">Password</label>
                                <input type="password" name="password" id="password" class="form-control" value="">
                            </div>
                            <div class="form-group mb-2">
                                <label for="password_confirmation">Confirm Password</label>
                                <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" value="">
                            </div>
                            @endif
                            <div class="mt-4 d-flex align-items-center justify-content-between">
                                <a href="{{route('admin.customers.index')}}" class="btn btn-outline-primary">Cancel</a>

                                <button type="submit" class="btn btn-primary">
                                    {{isset($customer) ? 'Update' : 'Save'}}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customer/home.blade.php
@extends('layouts.customer')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold pt-4 pb-1">Featured Products</h4>

        <div class="row">
            @foreach($popular_products as $product)
                <div class="col-md-3">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="d-flex align-items-center mb-3">
                                <img src="{{$product->brand->logo}}" alt="{{$product->brand->name}}" style="height: 32px;" class="me-2">
                            </div>
                            <h5 class="card-title">{{$product->name}}</h5>
                            <img class="img-fluid d-flex mx-auto my-3 rounded" src="{{ $product->image }}" alt="{{ $product->name }}">
                            <div class="mb-3">
                                <h4 class="card-text mb-0">
                                    {{$product->price}}
                                </h4>
                                <h6 class="text-warning fw-normal">
                                    <del>{{$product->from_price}}</del>
                                </h6>
                            </div>
                            <div class="row align-items-center d-flex">
                                <div class="col-7">
                                    <a href="javascript:void(0);" class="btn btn-outline-primary w-100 add-to-cart" data-id="{{$product->id}}">Add to Cart</a>
                                </div>
                                <div class="col-5">
                                    <a href="javascript:void(0);" class="card-link w-100 text-center">View Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        <h4 class="fw-bold pt-4 pb-1">New Products</h4>

        <div class="row">
            @foreach($new_products as $product)
                <div class="col-md-3">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="d-flex align-items-center mb-3">
                                <img src="{{$product->brand->logo}}" alt="{{$product->brand->name}}" style="height: 32px;" class="me-2">
                            </div>
                            <h5 class="card-title">{{$product->name}}</h5>
                            <img class="img-fluid d-flex mx-auto my-3 rounded" src="{{ $product->image }}" alt="{{ $product->name }}">
                            <div class="mb-3">
                                <h4 class="card-text mb-0">
                                    {{$product->price}}
                                </h4>
                                <h6 class="text-warning fw-normal">
                                    <del>{{$product->from_price}}</del>
                                </h6>
                            </div>
                            <div class="row align-items-center d-flex">
                                <div class="col-7">
                                    <a href="javascript:void(0);" class="btn btn-outline-primary w-100 add-to-cart" data-id="{{$product->id}}">Add to Cart</a>
                                </div>
                                <div class="col-5">
                                    <a href="javascript:void(0);" class="card-link w-100 text-center">View Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        <h4 class="fw-bold pt-4 pb-1">Brands</h4>
        <div class="d-flex align-items-center justify-content-between mb-4">
            @foreach(\App\Models\ProductBrand::orderBy('name')->get() as $brand)
                <a href="{{route('brand', $brand)}}">
                    <img src="{{$brand->logo}}" alt="{{$brand->name}}" style="height: 40px" class="mx-3">
                </a>
            @endforeach
        </div>

        <h4 class="fw-bold pt-4 pb-1">Categories</h4>
        <div class="d-flex align-items-center justify-content-between">
            @foreach(\App\Models\ProductCategory::get() as $category)
                <a href="{{route('category', $category)}}">
                    <h3>{{$category->name}}</h3>
                </a>
            @endforeach
        </div>
    </div>
@endsection

resources/views/customer/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">Customers</h4>
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">
                    List Cusmtomers
                </h5>
                <a href="{{route('admin.customers.create')}}" class="d-flex align-items-center">Add New Customer</a>
            </div>
            <div class="card-body p-4 border-top">
                <table class="table table-striped datatable">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Gender</td>
                        <td>Address</td>
                        <td>Created Date</td>
                        <td class="text-center">Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($customers as $i => $user)
                        <tr>
                            <td>{{$i+1}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->sex}}</td>
                            <td>{{$user->customer->address}}</td>
                            <td>{{$user->customer->created_at->format('F j, Y H:i')}}</td>
                            <td class="text-center">
                                <a href="{{route('admin.customers.edit', $user->customer)}}" data-bs-toggle="tooltip" data-bs-title="Edit">
                                    <i class="ti ti-edit"></i>
                                </a>
                                <a href="{{route('admin.customers.destroy', $user->customer)}}" data-bs-toggle="tooltip" data-bs-title="Delete" class="ms-2">
                                    <i class="ti ti-trash"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection